os: osx
osx_image: xcode11.2
language: swift

install:
  - gem install cocoapods
  - pod install --repo-update

script:
  - set -o pipefail && xcodebuild -scheme eStore -workspace eStore.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=13.2.2' build test | xcpretty --color
after_success:
  - bash <(curl -s https://codecov.io/bash)
