os: osx
osx_image: xcode10
language: swift

cache:
 - bundler
 - cocoapods

before_install:
  - gem install -v 2.0.1 bundler --no-rdoc --no-ri

install:
 - bundle install --path vendor/bundle

script:
  - bundle exec pod install
  - set -o pipefail && xcodebuild -scheme eStore -workspace eStore.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=12.0' build test | xcpretty --color
after_success:
  - bash <(curl -s https://codecov.io/bash)
